<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Service::create([
            'title' => 'Electrical Handyman Services',
            'description' => "Each handyman is paired with a set number of local families whose homes they become intimately familiar with - so they can make smarter recommendations and work more efficiently. You'll love seeing the same familiar face every visit, as will they.<br><br>Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.<br><br>We hand-select each of our handymen and handywomen. They are fully-employed by us and thoroughly vetted for quality as well as communication skills. They enjoy ongoing training, health benefits, and even equity.",
            'image' => 'uploads/example.png',
            'video_bg' => 'uploads/example.png',
            'video_url' => 'youtube link',
        ]);
        Service::create([
            'title' => 'Plumbing Handyman Services',
            'description' => "Each handyman is paired with a set number of local families whose homes they become intimately familiar with - so they can make smarter recommendations and work more efficiently. You'll love seeing the same familiar face every visit, as will they.<br><br>Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.<br><br>We hand-select each of our handymen and handywomen. They are fully-employed by us and thoroughly vetted for quality as well as communication skills. They enjoy ongoing training, health benefits, and even equity.",
            'image' => 'uploads/example.png',
            'video_bg' => 'uploads/example.png',
            'video_url' => 'uploads/example.png',
        ]);
        Service::create([
            'title' => 'General Home Maintenance',
            'description' => "Each handyman is paired with a set number of local families whose homes they become intimately familiar with - so they can make smarter recommendations and work more efficiently. You'll love seeing the same familiar face every visit, as will they.<br><br>Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.<br><br>We hand-select each of our handymen and handywomen. They are fully-employed by us and thoroughly vetted for quality as well as communication skills. They enjoy ongoing training, health benefits, and even equity.",
            'image' => 'uploads/example.png',
            'video_bg' => 'uploads/example.png',
            'video_url' => 'uploads/example.png',
        ]);
        Service::create([
            'title' => 'Blinds and Window Treatments',
            'description' => "Each handyman is paired with a set number of local families whose homes they become intimately familiar with - so they can make smarter recommendations and work more efficiently. You'll love seeing the same familiar face every visit, as will they.<br><br>Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.<br><br>We hand-select each of our handymen and handywomen. They are fully-employed by us and thoroughly vetted for quality as well as communication skills. They enjoy ongoing training, health benefits, and even equity.",
            'image' => 'uploads/example.png',
            'video_bg' => 'uploads/example.png',
            'video_url' => 'uploads/example.png',
        ]);
        Service::create([
            'title' => 'Doors and Windows',
            'description' => "Each handyman is paired with a set number of local families whose homes they become intimately familiar with - so they can make smarter recommendations and work more efficiently. You'll love seeing the same familiar face every visit, as will they.<br><br>Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.<br><br>We hand-select each of our handymen and handywomen. They are fully-employed by us and thoroughly vetted for quality as well as communication skills. They enjoy ongoing training, health benefits, and even equity.",
            'image' => 'uploads/example.png',
            'video_bg' => 'uploads/example.png',
            'video_url' => 'uploads/example.png',
        ]);
        Service::create([
            'title' => 'Drywall',
            'description' => "Each handyman is paired with a set number of local families whose homes they become intimately familiar with - so they can make smarter recommendations and work more efficiently. You'll love seeing the same familiar face every visit, as will they.<br><br>Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.<br><br>We hand-select each of our handymen and handywomen. They are fully-employed by us and thoroughly vetted for quality as well as communication skills. They enjoy ongoing training, health benefits, and even equity.",
            'image' => 'uploads/example.png',
            'video_bg' => 'uploads/example.png',
            'video_url' => 'uploads/example.png',
        ]);
        Service::create([
            'title' => 'TVs, Artwork, and Shelving',
            'description' => "Each handyman is paired with a set number of local families whose homes they become intimately familiar with - so they can make smarter recommendations and work more efficiently. You'll love seeing the same familiar face every visit, as will they.<br><br>Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.<br><br>We hand-select each of our handymen and handywomen. They are fully-employed by us and thoroughly vetted for quality as well as communication skills. They enjoy ongoing training, health benefits, and even equity.",
            'image' => 'uploads/example.png',
            'video_bg' => 'uploads/example.png',
            'video_url' => 'uploads/example.png',
        ]);
        Service::create([
            'title' => 'Furniture Assembly and Repairs',
            'description' => "Each handyman is paired with a set number of local families whose homes they become intimately familiar with - so they can make smarter recommendations and work more efficiently. You'll love seeing the same familiar face every visit, as will they.<br><br>Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.<br><br>We hand-select each of our handymen and handywomen. They are fully-employed by us and thoroughly vetted for quality as well as communication skills. They enjoy ongoing training, health benefits, and even equity.",
            'image' => 'uploads/example.png',
            'video_bg' => 'uploads/example.png',
            'video_url' => 'uploads/example.png',
        ]);
        Service::create([
            'title' => 'Smart Home, Wi-Fi, and EV Charging',
            'description' => "Each handyman is paired with a set number of local families whose homes they become intimately familiar with - so they can make smarter recommendations and work more efficiently. You'll love seeing the same familiar face every visit, as will they.<br><br>Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru. Become a member and skip the hassle of home upkeep and maintenance. See what we can do for you with a free, no-obligation home walk-thru.<br><br>We hand-select each of our handymen and handywomen. They are fully-employed by us and thoroughly vetted for quality as well as communication skills. They enjoy ongoing training, health benefits, and even equity.",
            'image' => 'uploads/example.png',
            'video_bg' => 'uploads/example.png',
            'video_url' => 'uploads/example.png',
        ]);
    }
}
